/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessorIndexRouteImport } from './routes/professor/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SupportNewRouteImport } from './routes/support/new'
import { Route as ProfessorUploadRouteImport } from './routes/professor/upload'
import { Route as ProfessorTicketsRouteImport } from './routes/professor/tickets'
import { Route as ProfessorAnalyticsRouteImport } from './routes/professor/analytics'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorIndexRoute = ProfessorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SupportNewRoute = SupportNewRouteImport.update({
  id: '/support/new',
  path: '/support/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorUploadRoute = ProfessorUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorTicketsRoute = ProfessorTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => ProfessorRoute,
} as any)
const ProfessorAnalyticsRoute = ProfessorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ProfessorRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-chat': typeof AiChatRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/professor/analytics': typeof ProfessorAnalyticsRoute
  '/professor/tickets': typeof ProfessorTicketsRoute
  '/professor/upload': typeof ProfessorUploadRoute
  '/support/new': typeof SupportNewRoute
  '/admin/': typeof AdminIndexRoute
  '/professor/': typeof ProfessorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/professor/analytics': typeof ProfessorAnalyticsRoute
  '/professor/tickets': typeof ProfessorTicketsRoute
  '/professor/upload': typeof ProfessorUploadRoute
  '/support/new': typeof SupportNewRoute
  '/admin': typeof AdminIndexRoute
  '/professor': typeof ProfessorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-chat': typeof AiChatRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/professor': typeof ProfessorRouteWithChildren
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/upload': typeof AdminUploadRoute
  '/professor/analytics': typeof ProfessorAnalyticsRoute
  '/professor/tickets': typeof ProfessorTicketsRoute
  '/professor/upload': typeof ProfessorUploadRoute
  '/support/new': typeof SupportNewRoute
  '/admin/': typeof AdminIndexRoute
  '/professor/': typeof ProfessorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-chat'
    | '/billing'
    | '/dashboard'
    | '/departments'
    | '/library'
    | '/login'
    | '/pending-approval'
    | '/professor'
    | '/progress'
    | '/register'
    | '/status'
    | '/admin/analytics'
    | '/admin/notifications'
    | '/admin/tickets'
    | '/admin/upload'
    | '/professor/analytics'
    | '/professor/tickets'
    | '/professor/upload'
    | '/support/new'
    | '/admin/'
    | '/professor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/billing'
    | '/dashboard'
    | '/departments'
    | '/library'
    | '/login'
    | '/pending-approval'
    | '/progress'
    | '/register'
    | '/status'
    | '/admin/analytics'
    | '/admin/notifications'
    | '/admin/tickets'
    | '/admin/upload'
    | '/professor/analytics'
    | '/professor/tickets'
    | '/professor/upload'
    | '/support/new'
    | '/admin'
    | '/professor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-chat'
    | '/billing'
    | '/dashboard'
    | '/departments'
    | '/library'
    | '/login'
    | '/pending-approval'
    | '/professor'
    | '/progress'
    | '/register'
    | '/status'
    | '/admin/analytics'
    | '/admin/notifications'
    | '/admin/tickets'
    | '/admin/upload'
    | '/professor/analytics'
    | '/professor/tickets'
    | '/professor/upload'
    | '/support/new'
    | '/admin/'
    | '/professor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiChatRoute: typeof AiChatRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  ProfessorRoute: typeof ProfessorRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  StatusRoute: typeof StatusRoute
  SupportNewRoute: typeof SupportNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/': {
      id: '/professor/'
      path: '/'
      fullPath: '/professor/'
      preLoaderRoute: typeof ProfessorIndexRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/support/new': {
      id: '/support/new'
      path: '/support/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof SupportNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/upload': {
      id: '/professor/upload'
      path: '/upload'
      fullPath: '/professor/upload'
      preLoaderRoute: typeof ProfessorUploadRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/tickets': {
      id: '/professor/tickets'
      path: '/tickets'
      fullPath: '/professor/tickets'
      preLoaderRoute: typeof ProfessorTicketsRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/professor/analytics': {
      id: '/professor/analytics'
      path: '/analytics'
      fullPath: '/professor/analytics'
      preLoaderRoute: typeof ProfessorAnalyticsRouteImport
      parentRoute: typeof ProfessorRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfessorRouteChildren {
  ProfessorAnalyticsRoute: typeof ProfessorAnalyticsRoute
  ProfessorTicketsRoute: typeof ProfessorTicketsRoute
  ProfessorUploadRoute: typeof ProfessorUploadRoute
  ProfessorIndexRoute: typeof ProfessorIndexRoute
}

const ProfessorRouteChildren: ProfessorRouteChildren = {
  ProfessorAnalyticsRoute: ProfessorAnalyticsRoute,
  ProfessorTicketsRoute: ProfessorTicketsRoute,
  ProfessorUploadRoute: ProfessorUploadRoute,
  ProfessorIndexRoute: ProfessorIndexRoute,
}

const ProfessorRouteWithChildren = ProfessorRoute._addFileChildren(
  ProfessorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiChatRoute: AiChatRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  ProfessorRoute: ProfessorRouteWithChildren,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  StatusRoute: StatusRoute,
  SupportNewRoute: SupportNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
