/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyIndexRouteImport } from './routes/study/index'
import { Route as StudyNewRouteImport } from './routes/study/new'
import { Route as StudyKitIdIndexRouteImport } from './routes/study/$kitId/index'
import { Route as StudyKitIdTestRouteImport } from './routes/study/$kitId/test'
import { Route as StudyKitIdSummaryRouteImport } from './routes/study/$kitId/summary'
import { Route as StudyKitIdSmartStudyRouteImport } from './routes/study/$kitId/smart-study'
import { Route as StudyKitIdGuideRouteImport } from './routes/study/$kitId/guide'
import { Route as StudyKitIdFlashcardsRouteImport } from './routes/study/$kitId/flashcards'
import { Route as StudyKitIdPlayStackerRouteImport } from './routes/study/$kitId/play/stacker'
import { Route as StudyKitIdPlayMatchRouteImport } from './routes/study/$kitId/play/match'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyIndexRoute = StudyIndexRouteImport.update({
  id: '/study/',
  path: '/study/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyNewRoute = StudyNewRouteImport.update({
  id: '/study/new',
  path: '/study/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyKitIdIndexRoute = StudyKitIdIndexRouteImport.update({
  id: '/study/$kitId/',
  path: '/study/$kitId/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyKitIdTestRoute = StudyKitIdTestRouteImport.update({
  id: '/study/$kitId/test',
  path: '/study/$kitId/test',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyKitIdSummaryRoute = StudyKitIdSummaryRouteImport.update({
  id: '/study/$kitId/summary',
  path: '/study/$kitId/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyKitIdSmartStudyRoute = StudyKitIdSmartStudyRouteImport.update({
  id: '/study/$kitId/smart-study',
  path: '/study/$kitId/smart-study',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyKitIdGuideRoute = StudyKitIdGuideRouteImport.update({
  id: '/study/$kitId/guide',
  path: '/study/$kitId/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyKitIdFlashcardsRoute = StudyKitIdFlashcardsRouteImport.update({
  id: '/study/$kitId/flashcards',
  path: '/study/$kitId/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyKitIdPlayStackerRoute = StudyKitIdPlayStackerRouteImport.update({
  id: '/study/$kitId/play/stacker',
  path: '/study/$kitId/play/stacker',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyKitIdPlayMatchRoute = StudyKitIdPlayMatchRouteImport.update({
  id: '/study/$kitId/play/match',
  path: '/study/$kitId/play/match',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/study/new': typeof StudyNewRoute
  '/study/': typeof StudyIndexRoute
  '/study/$kitId/flashcards': typeof StudyKitIdFlashcardsRoute
  '/study/$kitId/guide': typeof StudyKitIdGuideRoute
  '/study/$kitId/smart-study': typeof StudyKitIdSmartStudyRoute
  '/study/$kitId/summary': typeof StudyKitIdSummaryRoute
  '/study/$kitId/test': typeof StudyKitIdTestRoute
  '/study/$kitId/': typeof StudyKitIdIndexRoute
  '/study/$kitId/play/match': typeof StudyKitIdPlayMatchRoute
  '/study/$kitId/play/stacker': typeof StudyKitIdPlayStackerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/study/new': typeof StudyNewRoute
  '/study': typeof StudyIndexRoute
  '/study/$kitId/flashcards': typeof StudyKitIdFlashcardsRoute
  '/study/$kitId/guide': typeof StudyKitIdGuideRoute
  '/study/$kitId/smart-study': typeof StudyKitIdSmartStudyRoute
  '/study/$kitId/summary': typeof StudyKitIdSummaryRoute
  '/study/$kitId/test': typeof StudyKitIdTestRoute
  '/study/$kitId': typeof StudyKitIdIndexRoute
  '/study/$kitId/play/match': typeof StudyKitIdPlayMatchRoute
  '/study/$kitId/play/stacker': typeof StudyKitIdPlayStackerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/departments': typeof DepartmentsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/register': typeof RegisterRoute
  '/status': typeof StatusRoute
  '/study/new': typeof StudyNewRoute
  '/study/': typeof StudyIndexRoute
  '/study/$kitId/flashcards': typeof StudyKitIdFlashcardsRoute
  '/study/$kitId/guide': typeof StudyKitIdGuideRoute
  '/study/$kitId/smart-study': typeof StudyKitIdSmartStudyRoute
  '/study/$kitId/summary': typeof StudyKitIdSummaryRoute
  '/study/$kitId/test': typeof StudyKitIdTestRoute
  '/study/$kitId/': typeof StudyKitIdIndexRoute
  '/study/$kitId/play/match': typeof StudyKitIdPlayMatchRoute
  '/study/$kitId/play/stacker': typeof StudyKitIdPlayStackerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/billing'
    | '/dashboard'
    | '/departments'
    | '/library'
    | '/login'
    | '/progress'
    | '/register'
    | '/status'
    | '/study/new'
    | '/study/'
    | '/study/$kitId/flashcards'
    | '/study/$kitId/guide'
    | '/study/$kitId/smart-study'
    | '/study/$kitId/summary'
    | '/study/$kitId/test'
    | '/study/$kitId/'
    | '/study/$kitId/play/match'
    | '/study/$kitId/play/stacker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/billing'
    | '/dashboard'
    | '/departments'
    | '/library'
    | '/login'
    | '/progress'
    | '/register'
    | '/status'
    | '/study/new'
    | '/study'
    | '/study/$kitId/flashcards'
    | '/study/$kitId/guide'
    | '/study/$kitId/smart-study'
    | '/study/$kitId/summary'
    | '/study/$kitId/test'
    | '/study/$kitId'
    | '/study/$kitId/play/match'
    | '/study/$kitId/play/stacker'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/billing'
    | '/dashboard'
    | '/departments'
    | '/library'
    | '/login'
    | '/progress'
    | '/register'
    | '/status'
    | '/study/new'
    | '/study/'
    | '/study/$kitId/flashcards'
    | '/study/$kitId/guide'
    | '/study/$kitId/smart-study'
    | '/study/$kitId/summary'
    | '/study/$kitId/test'
    | '/study/$kitId/'
    | '/study/$kitId/play/match'
    | '/study/$kitId/play/stacker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  DepartmentsRoute: typeof DepartmentsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  RegisterRoute: typeof RegisterRoute
  StatusRoute: typeof StatusRoute
  StudyNewRoute: typeof StudyNewRoute
  StudyIndexRoute: typeof StudyIndexRoute
  StudyKitIdFlashcardsRoute: typeof StudyKitIdFlashcardsRoute
  StudyKitIdGuideRoute: typeof StudyKitIdGuideRoute
  StudyKitIdSmartStudyRoute: typeof StudyKitIdSmartStudyRoute
  StudyKitIdSummaryRoute: typeof StudyKitIdSummaryRoute
  StudyKitIdTestRoute: typeof StudyKitIdTestRoute
  StudyKitIdIndexRoute: typeof StudyKitIdIndexRoute
  StudyKitIdPlayMatchRoute: typeof StudyKitIdPlayMatchRoute
  StudyKitIdPlayStackerRoute: typeof StudyKitIdPlayStackerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/': {
      id: '/study/'
      path: '/study'
      fullPath: '/study/'
      preLoaderRoute: typeof StudyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/new': {
      id: '/study/new'
      path: '/study/new'
      fullPath: '/study/new'
      preLoaderRoute: typeof StudyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$kitId/': {
      id: '/study/$kitId/'
      path: '/study/$kitId'
      fullPath: '/study/$kitId/'
      preLoaderRoute: typeof StudyKitIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$kitId/test': {
      id: '/study/$kitId/test'
      path: '/study/$kitId/test'
      fullPath: '/study/$kitId/test'
      preLoaderRoute: typeof StudyKitIdTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$kitId/summary': {
      id: '/study/$kitId/summary'
      path: '/study/$kitId/summary'
      fullPath: '/study/$kitId/summary'
      preLoaderRoute: typeof StudyKitIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$kitId/smart-study': {
      id: '/study/$kitId/smart-study'
      path: '/study/$kitId/smart-study'
      fullPath: '/study/$kitId/smart-study'
      preLoaderRoute: typeof StudyKitIdSmartStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$kitId/guide': {
      id: '/study/$kitId/guide'
      path: '/study/$kitId/guide'
      fullPath: '/study/$kitId/guide'
      preLoaderRoute: typeof StudyKitIdGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$kitId/flashcards': {
      id: '/study/$kitId/flashcards'
      path: '/study/$kitId/flashcards'
      fullPath: '/study/$kitId/flashcards'
      preLoaderRoute: typeof StudyKitIdFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$kitId/play/stacker': {
      id: '/study/$kitId/play/stacker'
      path: '/study/$kitId/play/stacker'
      fullPath: '/study/$kitId/play/stacker'
      preLoaderRoute: typeof StudyKitIdPlayStackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study/$kitId/play/match': {
      id: '/study/$kitId/play/match'
      path: '/study/$kitId/play/match'
      fullPath: '/study/$kitId/play/match'
      preLoaderRoute: typeof StudyKitIdPlayMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  DepartmentsRoute: DepartmentsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  RegisterRoute: RegisterRoute,
  StatusRoute: StatusRoute,
  StudyNewRoute: StudyNewRoute,
  StudyIndexRoute: StudyIndexRoute,
  StudyKitIdFlashcardsRoute: StudyKitIdFlashcardsRoute,
  StudyKitIdGuideRoute: StudyKitIdGuideRoute,
  StudyKitIdSmartStudyRoute: StudyKitIdSmartStudyRoute,
  StudyKitIdSummaryRoute: StudyKitIdSummaryRoute,
  StudyKitIdTestRoute: StudyKitIdTestRoute,
  StudyKitIdIndexRoute: StudyKitIdIndexRoute,
  StudyKitIdPlayMatchRoute: StudyKitIdPlayMatchRoute,
  StudyKitIdPlayStackerRoute: StudyKitIdPlayStackerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
